library(RSQLite)

set.seed(176400)

defaultDbFile <- "testDb.sqlite"

# Helper Functions --------------------------------------------------------

# This function takes settings and returns a list of data frames which can be used for testing, including a cohort
# table that can be run through the SQL files. The building blocks of that cohort data can be used to verify the
# correctness of the SQL.
generateTestData <- function(
  n,
  targetId,
  outcomeIds,
  proportionSecondShot,
  riskWindowAfterTargetExposureDays,
  washoutPeriodDays,
  highRiskGroupDefinition,
  matchHighRiskCriteria,
  lowRiskTargetIncidence,
  lowRiskComparatorIncidence,
  highRiskTargetIncidence,
  highRiskComparatorIncidence,
  studyStartDate,
  studyEndDate
) {
  targetDaysEligibleBeforeStudyEndDate <- as.integer(as.Date(studyEndDate) - as.Date(studyStartDate))

  persons <- generateSimulatedPersonsData(n)

  cohort <- generateSimulatedCohortTable(
      persons = persons,
      targetId = targetId,
      outcomeIds = outcomeIds,
      proportionSecondShot = proportionSecondShot,
      riskWindowAfterTargetExposureDays = riskWindowAfterTargetExposureDays,
      washoutPeriodDays = washoutPeriodDays,
      highRiskGroupDefinition = highRiskGroupDefinition,
      matchHighRiskCriteria = matchHighRiskCriteria,
      lowRiskTargetIncidence = lowRiskTargetIncidence,
      lowRiskComparatorIncidence = lowRiskComparatorIncidence,
      highRiskTargetIncidence = highRiskTargetIncidence,
      highRiskComparatorIncidence = highRiskComparatorIncidence,
      studyEndDate = studyEndDate,
      targetDaysEligibleBeforeStudyEndDate = targetDaysEligibleBeforeStudyEndDate
  )

  observationPeriods <- generateSimulatedObservationPeriodTable(cohort, washoutPeriodDays)

  targetCohort <- generateTargetCohortFromSimulatedCohortTable(
      cohort,
      targetCohortId = targetId,
      riskWindowAfterTargetExposureDays = riskWindowAfterTargetExposureDays
  )

  comparatorCohort <- generateComparatorCohortFromSimulatedTargetCohortTable(
      targetCohort,
      washoutPeriodDays = washoutPeriodDays,
      riskWindowAfterTargetExposureDays = riskWindowAfterTargetExposureDays
  )

  strata <- generateStrataFromCohort(targetCohort, persons)

  matchedStrata <- generateMatchedStrataForComparatorCohort(strata, comparatorCohort, persons)

  matchedCohort <- generateMatchedCohort(targetCohort, comparatorCohort, matchedStrata, persons)

  allOutcomes <- getOutcomesForMatchedCohort(
      cohort,
      matchedCohort,
      targetId = targetId,
      outcomeIds = outcomeIds,
      daysFromObsStart = 1,
      daysToObsEnd = riskWindowAfterTargetExposureDays
  )

  # SQLite does not have datetimes. By default, RSQLite will convert dates to days before/after unix epoch
  # This is not ideal for our purposes because OHDSI tooling, such as the SQL generated by SQL translation functions
  # assumes that dates are stored as dates. Typically, storing the data as unix timestamps, i.e., as the number of
  # seconds since the unix epoch, allows us to work around this problem.
  #
  # For this reason, we will also return SQLite ready dataframes, where dates have been pre-converted to unix timestamps.
  # It's easiest to return the unaltered dataframes, in addition to SQLite ready ones, to allow for easy manipulation.
  sqlitePerson <- persons %>% mutate(
      birth_datetime = as.numeric(as.POSIXct(birth_datetime), format = "%Y-%m-%d")
  )

  sqliteCohort <- cohort %>% mutate(
      cohort_start_date = as.numeric(as.POSIXct(cohort_start_date), format = "%Y-%m-%d"),
      cohort_end_date = as.numeric(as.POSIXct(cohort_end_date), format = "%Y-%m-%d")
  )

  sqliteObservationPeriod <- observationPeriods %>% mutate(
      observation_period_start_date = as.numeric(as.POSIXct(observation_period_start_date), format = "%Y-%m-%d"),
      observation_period_end_date = as.numeric(as.POSIXct(observation_period_end_date), format = "%Y-%m-%d")
  )

  return(
    list(
        cohort = cohort,
        persons = persons,
        observationPeriods = observationPeriods,
        targetCohort = targetCohort,
        comparatorCohort = comparatorCohort,
        strata = strata,
        matchedStrata = matchedStrata,
        matchedCohort = matchedCohort,
        allOutcomes = allOutcomes,
        sqlitePerson = sqlitePerson,
        sqliteCohort = sqliteCohort,
        sqliteObservationPeriod = sqliteObservationPeriod
    )
  )
}

createEmptySQLiteDb <- function(dbFile) {
    con <- dbConnect(RSQLite::SQLite(), dbFile)
    dbDisconnect(con)
}

createPersonsTable <- function(persons, schema, personsTable, dbFile) {
    con <- RSQLite::dbConnect(RSQLite::SQLite(), dbFile)
    RSQLite::dbWriteTable(con, Id(schema = schema, table = personsTable), persons, overwrite = TRUE)
    RSQLite::dbDisconnect(con)
}

createCohortTable <- function(cohort, schema, cohortTable, dbFile) {
    con <- RSQLite::dbConnect(RSQLite::SQLite(), dbFile)
    RSQLite::dbWriteTable(con, Id(schema = schema, table = cohortTable), cohort, overwrite = TRUE)
    RSQLite::dbDisconnect(con)
}

createObservationPeriodTable <- function(observationPeriods, schema, observationPeriodTable, dbFile) {
    con <- RSQLite::dbConnect(RSQLite::SQLite(), dbFile)
    RSQLite::dbWriteTable(con, Id(schema = schema, table = observationPeriodTable), observationPeriods, overwrite = TRUE)
    RSQLite::dbDisconnect(con)
}

scaffoldTestData <- function(
    n = 1000,
    targetId = 666,
    outcomeIds = c(668),
    proportionSecondShot = 1,
    riskWindowAfterTargetExposureDays = 21,
    washoutPeriodDays = 22,
    highRiskGroupDefinition = list(),
    matchHighRiskCriteria = 'all',
    lowRiskTargetIncidence = 0.01,
    lowRiskComparatorIncidence = 0.01,
    highRiskTargetIncidence = 0.01,
    highRiskComparatorIncidence = 0.01,
    studyStartDate = '2020-12-18',
    studyEndDate = '2021-06-30',
    dbFile = "testDb.sqlite",
    cdmDatabaseSchema = "main",
    personsTable = "person",
    cohortTable = "cohort",
    observationPeriodTable = "observation_period"
) {

    createEmptySQLiteDb(dbFile)

    data <- generateTestData(
        n,
        targetId,
        outcomeIds,
        proportionSecondShot,
        riskWindowAfterTargetExposureDays,
        washoutPeriodDays,
        highRiskGroupDefinition,
        matchHighRiskCriteria,
        lowRiskTargetIncidence,
        lowRiskComparatorIncidence,
        highRiskTargetIncidence,
        highRiskComparatorIncidence,
        studyStartDate,
        studyEndDate
    )

    createPersonsTable(data$sqlitePerson, cdmDatabaseSchema, personsTable, dbFile)
    createCohortTable(data$sqliteCohort, cdmDatabaseSchema, cohortTable, dbFile)
    createObservationPeriodTable(data$sqliteObservationPeriod, cdmDatabaseSchema, observationPeriodTable, dbFile)

    sqliteConnectionDetails <- DatabaseConnector::createConnectionDetails(
        dbms = "sqlite",
        server = dbFile
    )
    sqliteConnection <- DatabaseConnector::connect(sqliteConnectionDetails)

    writeMatchedCohortsToScratchDatabase(sqliteConnection,
                                         "sqlite",
                                         cdmDatabaseSchema,
                                         cdmDatabaseSchema,
                                         cohortTable,
                                         riskWindowAfterTargetExposureDays,
                                         washoutPeriodDays,
                                         targetId)

    settings <- list(
        n = n,
        targetId = targetId,
        outcomeIds = outcomeIds,
        proportionSecondShot = proportionSecondShot,
        riskWindowAfterTargetExposureDays = riskWindowAfterTargetExposureDays,
        washoutPeriodDays = washoutPeriodDays,
        highRiskGroupDefinition = highRiskGroupDefinition,
        matchHighRiskCriteria = matchHighRiskCriteria,
        lowRiskTargetIncidence = lowRiskTargetIncidence,
        lowRiskComparatorIncidence = lowRiskComparatorIncidence,
        highRiskTargetIncidence = highRiskTargetIncidence,
        highRiskComparatorIncidence = highRiskComparatorIncidence,
        studyStartDate = studyStartDate,
        studyEndDate = studyEndDate,
        dbFile = dbFile,
        cdmDatabaseSchema = cdmDatabaseSchema,
        personsTable = personsTable,
        cohortTable = cohortTable,
        observationPeriodTable = observationPeriodTable
    )

    return(
      list(
          data = data,
          settings = settings,
          dbFile = dbFile,
          sqliteConnection = sqliteConnection
      )
    )
}

getStrataCountFromData <- function(cohort, targetId, persons) {
        cohort %>%
        filter(cohort_definition_id == targetId) %>%
        unique() %>%
        inner_join(
            persons %>% select(
                person_id,
                gender_concept_id,
                race_concept_id,
                ethnicity_concept_id,
                year_of_birth
            ),
            by = c("subject_id" = "person_id")
        ) %>%
        mutate(
            age_group_id = round((year(
                as.POSIXct(cohort_start_date, origin = "1970-01-01")
            ) - year_of_birth) / 5),
            unique_id = paste(
                cohort_start_date,
                age_group_id,
                gender_concept_id,
                race_concept_id,
                ethnicity_concept_id,
                sep = "_"
            )
        ) %>%
        distinct(unique_id) %>%
        count() %>%
        pull(n)
}

withr::defer(unlink(defaultDbFile), teardown_env())
