library(RSQLite)

set.seed(176400)

defaultDbFile <- "testDb.sqlite"

# Helper Functions --------------------------------------------------------

# This function takes settings and returns a list of data frames which can be used for testing, including a cohort
# table that can be run through the SQL files. The building blocks of that cohort data can be used to verify the
# correctness of the SQL.
generateTestSourceData <- function(
  n,
  targetId,
  outcomeIds,
  proportionSecondShot,
  timeAtRiskStartDays,
  timeAtRiskEndDays,
  washoutPeriodDays,
  highRiskGroupDefinition,
  matchHighRiskCriteria,
  lowRiskTargetIncidence,
  lowRiskComparatorIncidence,
  highRiskTargetIncidence,
  highRiskComparatorIncidence,
  studyStartDate,
  studyEndDate
) {
  targetDaysEligibleBeforeStudyEndDate <- as.integer(as.Date(studyEndDate) - as.Date(studyStartDate))

  persons <- generateSimulatedPersonsData(n)

  cohort <- generateSimulatedCohortTable(
      persons = persons,
      targetId = targetId,
      outcomeIds = outcomeIds,
      proportionSecondShot = proportionSecondShot,
      timeAtRiskEndDays = timeAtRiskEndDays,
      washoutPeriodDays = washoutPeriodDays,
      highRiskGroupDefinition = highRiskGroupDefinition,
      matchHighRiskCriteria = matchHighRiskCriteria,
      lowRiskTargetIncidence = lowRiskTargetIncidence,
      lowRiskComparatorIncidence = lowRiskComparatorIncidence,
      highRiskTargetIncidence = highRiskTargetIncidence,
      highRiskComparatorIncidence = highRiskComparatorIncidence,
      studyEndDate = studyEndDate,
      targetDaysEligibleBeforeStudyEndDate = targetDaysEligibleBeforeStudyEndDate
  )

  observationPeriods <- generateSimulatedObservationPeriodTable(cohort, washoutPeriodDays)

  targetCohort <- generateTargetCohortFromSimulatedCohortTable(
      cohort,
      targetCohortId = targetId,
      timeAtRiskEndDays = timeAtRiskEndDays
  )

  comparatorCohort <- generateComparatorCohortFromSimulatedTargetCohortTable(
      targetCohort,
      washoutPeriodDays = washoutPeriodDays,
      timeAtRiskEndDays = timeAtRiskEndDays
  )

  strata <- generateStrataFromCohort(targetCohort, persons)

  matchedStrata <- generateMatchedStrataForComparatorCohort(strata, comparatorCohort, persons)

  matchedCohort <- generateMatchedCohort(targetCohort, comparatorCohort, matchedStrata, persons)

  allOutcomes <- getOutcomesForMatchedCohort(
      cohort,
      matchedCohort,
      targetId = targetId,
      outcomeIds = outcomeIds,
      daysFromObsStart = timeAtRiskStartDays,
      daysToObsEnd = timeAtRiskEndDays
  )

  # SQLite does not have datetimes. By default, RSQLite will convert dates to days before/after unix epoch
  # This is not ideal for our purposes because OHDSI tooling, such as the SQL generated by SQL translation functions
  # assumes that dates are stored as dates. Typically, storing the data as unix timestamps, i.e., as the number of
  # seconds since the unix epoch, allows us to work around this problem.
  #
  # For this reason, we will also return SQLite ready dataframes, where dates have been pre-converted to unix timestamps.
  # It's easiest to return the unaltered dataframes, in addition to SQLite ready ones, to allow for easy manipulation.
  sqlitePerson <- persons %>% mutate(
      birth_datetime = as.numeric(as.POSIXct(birth_datetime), format = "%Y-%m-%d")
  )

  sqliteCohort <- cohort %>% mutate(
      cohort_start_date = as.numeric(as.POSIXct(cohort_start_date), format = "%Y-%m-%d"),
      cohort_end_date = as.numeric(as.POSIXct(cohort_end_date), format = "%Y-%m-%d")
  )

  sqliteObservationPeriod <- observationPeriods %>% mutate(
      observation_period_start_date = as.numeric(as.POSIXct(observation_period_start_date), format = "%Y-%m-%d"),
      observation_period_end_date = as.numeric(as.POSIXct(observation_period_end_date), format = "%Y-%m-%d")
  )

  return(
    list(
        cohort = cohort,
        persons = persons,
        observationPeriods = observationPeriods,
        targetCohort = targetCohort,
        comparatorCohort = comparatorCohort,
        strata = strata,
        matchedStrata = matchedStrata,
        matchedCohort = matchedCohort,
        allOutcomes = allOutcomes,
        sqlitePerson = sqlitePerson,
        sqliteCohort = sqliteCohort,
        sqliteObservationPeriod = sqliteObservationPeriod
    )
  )
}

createEmptySQLiteDb <- function(dbFile) {
    con <- dbConnect(RSQLite::SQLite(), dbFile)
    RSQLite::dbDisconnect(con)
}

createPersonsTable <- function(persons, schema, personsTable, dbFile) {
    con <- RSQLite::dbConnect(RSQLite::SQLite(), dbFile)
    RSQLite::dbWriteTable(con, Id(schema = schema, table = personsTable), persons, overwrite = TRUE)
    RSQLite::dbDisconnect(con)
}

createCohortTable <- function(cohort, schema, cohortTable, dbFile) {
    con <- RSQLite::dbConnect(RSQLite::SQLite(), dbFile)
    RSQLite::dbWriteTable(con, Id(schema = schema, table = cohortTable), cohort, overwrite = TRUE)
    RSQLite::dbDisconnect(con)
}

createObservationPeriodTable <- function(observationPeriods, schema, observationPeriodTable, dbFile) {
    con <- RSQLite::dbConnect(RSQLite::SQLite(), dbFile)
    RSQLite::dbWriteTable(con, Id(schema = schema, table = observationPeriodTable), observationPeriods, overwrite = TRUE)
    RSQLite::dbDisconnect(con)
}


# Specify outcomes in a list of lists, where each list contains the outcomeId and the number of days after the first shot.
# For example:
#
# list(
#     list(outcomeId = 1,
#         daysAfterLastShot = 7),
#     list(outcomeId = 2,
#         daysAfterLastShot = 30)
# )

scaffoldN2TestData <- function(
    targetId = 666,
    outcomeIds = c(668),
    outcomes = list(),
    secondShot = TRUE,
    shot1Day = "2020-04-01",
    daysBetweenShots = 30,
    timeAtRiskStartDays = 1,
    timeAtRiskEndDays = 21,
    washoutPeriodDays = 22,
    comparatorShotDaysBefore = 22,  # Match to washout to make them share stratum
    dbFile = "testDb.sqlite",
    cdmDatabaseSchema = "main",
    personsTable = "person",
    cohortTable = "cohort",
    observationPeriodTable = "observation_period"
) {
  createEmptySQLiteDb(dbFile)

  shot1Day <- as.Date(shot1Day)
  shotDay <- shot1Day

  # Generate a person
  targetPerson <- generateSimulatedPersonsData(1)

  # Generate a person who will match strata of this person
  comparatorPerson <- targetPerson %>% mutate(
      person_id = 2
  )

  # Combine
  person <- rbind(targetPerson, comparatorPerson)

  # Target: First shot
  cohort <- tribble(
      ~cohort_definition_id, ~subject_id, ~cohort_start_date, ~cohort_end_date,
      targetId, 1, shotDay, shotDay + 1
  )

  # Target: Second shot, if defined
  if(secondShot) {
    shot2Day <- shotDay + daysBetweenShots
    cohort <- rbind(cohort, tribble(
        ~cohort_definition_id, ~subject_id, ~cohort_start_date, ~cohort_end_date,
        targetId, 1, shot2Day, shot2Day + 1
    ))
  }

  # Person 2: Comparator match. Gets shot washoutPeriodDays before the first shot of Target
  # This is to ensure this match enters the comparator cohort at the same time as the target cohort
  # gets a shot.
  comparatorStartDay <- shot1Day - comparatorShotDaysBefore
  cohort <- rbind(cohort, tribble(
      ~cohort_definition_id, ~subject_id, ~cohort_start_date, ~cohort_end_date,
      targetId, 2, comparatorStartDay, comparatorStartDay + 1
  ))

  # Create outcomes
  if(length(outcomes) > 0) {
      for(outcome in outcomes) {
          targetOutcomeDay <- shot1Day + outcome$daysAfterFirstShot
          comparatorOutcomeDay <- comparatorStartDay + outcome$daysAfterFirstShot
          cohort <- rbind(cohort, tribble(
              ~cohort_definition_id, ~subject_id, ~cohort_start_date, ~cohort_end_date,
              outcome$outcomeId, 1, targetOutcomeDay, targetOutcomeDay + 1,
              outcome$outcomeId, 2, comparatorOutcomeDay, comparatorOutcomeDay + 1
          ))
      }
  }

  person1MinDay <- cohort %>% filter(subject_id == 1) %>% pull(cohort_start_date) %>% min() - 1
  person1MaxDay <- cohort %>% filter(subject_id == 1) %>% pull(cohort_end_date) %>% max() + 1 + 2*washoutPeriodDays
  person2MinDay <- cohort %>% filter(subject_id == 2) %>% pull(cohort_start_date) %>% min() - 1
  person2MaxDay <- cohort %>% filter(subject_id == 2) %>% pull(cohort_end_date) %>% max() + 1 + 2*washoutPeriodDays

  observationPeriods <- tribble(
      ~person_id, ~observation_period_start_date, ~observation_period_end_date,
      1, person1MinDay, person1MaxDay,
      2, person2MinDay, person2MaxDay
  )

  # make SQLite ready dataframes by converting dates to unix timestamps
  sqlitePerson <- person %>% mutate(
      birth_datetime = as.numeric(as.POSIXct(birth_datetime), format = "%Y-%m-%d")
  )

  sqliteCohort <- cohort %>% mutate(
      cohort_start_date = as.numeric(as.POSIXct(cohort_start_date), format = "%Y-%m-%d"),
      cohort_end_date = as.numeric(as.POSIXct(cohort_end_date), format = "%Y-%m-%d")
  )

  sqliteObservationPeriod <- observationPeriods %>% mutate(
      observation_period_start_date = as.numeric(as.POSIXct(observation_period_start_date), format = "%Y-%m-%d"),
      observation_period_end_date = as.numeric(as.POSIXct(observation_period_end_date), format = "%Y-%m-%d")
  )

  createPersonsTable(sqlitePerson, cdmDatabaseSchema, personsTable, dbFile)
  createCohortTable(sqliteCohort, cdmDatabaseSchema, cohortTable, dbFile)
  createObservationPeriodTable(sqliteObservationPeriod, cdmDatabaseSchema, observationPeriodTable, dbFile)

  sqliteConnectionDetails <- DatabaseConnector::createConnectionDetails(
      dbms = "sqlite",
      server = dbFile
  )

  ccData <- getDbConcurrentComparatorData(connectionDetails = sqliteConnectionDetails,
                                          cdmDatabaseSchema = cdmDatabaseSchema,
                                          targetId = targetId,
                                          outcomeIds = outcomeIds,
                                          exposureDatabaseSchema = cdmDatabaseSchema,
                                          exposureTable = cohortTable,
                                          outcomeDatabaseSchema = cdmDatabaseSchema,
                                          outcomeTable = cohortTable,
                                          timeAtRiskStart = timeAtRiskStartDays,
                                          timeAtRiskEnd = timeAtRiskEndDays,
                                          washoutTime = washoutPeriodDays,
                                          intermediateFileNameStem = NULL)

  settings <- list(
      targetId = targetId,
      outcomes = outcomes,
      secondShot = secondShot,
      shot1Day = shot1Day,
      daysBetweenShots = daysBetweenShots,
      timeAtRiskStartDays = timeAtRiskStartDays,
      timeAtRiskEndDays = timeAtRiskEndDays,
      washoutPeriodDays = washoutPeriodDays,
      comparatorShotDaysBefore = comparatorShotDaysBefore,
      dbFile = dbFile,
      cdmDatabaseSchema = cdmDatabaseSchema,
      personsTable = personsTable,
      cohortTable = cohortTable,
      observationPeriodTable = observationPeriodTable
  )

  return(list(
      ccData = ccData,
      settings = settings
  ))
}

scaffoldTestData <- function(
    n = 1000,
    targetId = 666,
    outcomeIds = c(668),
    proportionSecondShot = 1,
    timeAtRiskStartDays = 1,
    timeAtRiskEndDays = 21,
    washoutPeriodDays = 22,
    highRiskGroupDefinition = list(),
    matchHighRiskCriteria = 'all',
    lowRiskTargetIncidence = 0.01,
    lowRiskComparatorIncidence = 0.01,
    highRiskTargetIncidence = 0.01,
    highRiskComparatorIncidence = 0.01,
    studyStartDate = '2020-12-18',
    studyEndDate = '2021-06-30',
    dbFile = "testDb.sqlite",
    cdmDatabaseSchema = "main",
    personsTable = "person",
    cohortTable = "cohort",
    observationPeriodTable = "observation_period"
) {
    createEmptySQLiteDb(dbFile)

    data <- generateTestSourceData(
        n,
        targetId,
        outcomeIds,
        proportionSecondShot,
        timeAtRiskStartDays,
        timeAtRiskEndDays,
        washoutPeriodDays,
        highRiskGroupDefinition,
        matchHighRiskCriteria,
        lowRiskTargetIncidence,
        lowRiskComparatorIncidence,
        highRiskTargetIncidence,
        highRiskComparatorIncidence,
        studyStartDate,
        studyEndDate
    )

    createPersonsTable(data$sqlitePerson, cdmDatabaseSchema, personsTable, dbFile)
    createCohortTable(data$sqliteCohort, cdmDatabaseSchema, cohortTable, dbFile)
    createObservationPeriodTable(data$sqliteObservationPeriod, cdmDatabaseSchema, observationPeriodTable, dbFile)

    sqliteConnectionDetails <- DatabaseConnector::createConnectionDetails(
        dbms = "sqlite",
        server = dbFile
    )

    ccData <- getDbConcurrentComparatorData(connectionDetails = sqliteConnectionDetails,
                                            cdmDatabaseSchema = cdmDatabaseSchema,
                                            targetId = targetId,
                                            outcomeIds = outcomeIds,
                                            studyEndDate = studyEndDate,
                                            exposureDatabaseSchema = cdmDatabaseSchema,
                                            exposureTable = cohortTable,
                                            outcomeDatabaseSchema = cdmDatabaseSchema,
                                            outcomeTable = cohortTable,
                                            timeAtRiskStart = timeAtRiskStartDays,
                                            timeAtRiskEnd = timeAtRiskEndDays,
                                            washoutTime = washoutPeriodDays,
                                            intermediateFileNameStem = NULL)

    settings <- list(
        n = n,
        targetId = targetId,
        outcomeIds = outcomeIds,
        proportionSecondShot = proportionSecondShot,
        timeAtRiskEndDays = timeAtRiskEndDays,
        washoutPeriodDays = washoutPeriodDays,
        highRiskGroupDefinition = highRiskGroupDefinition,
        matchHighRiskCriteria = matchHighRiskCriteria,
        lowRiskTargetIncidence = lowRiskTargetIncidence,
        lowRiskComparatorIncidence = lowRiskComparatorIncidence,
        highRiskTargetIncidence = highRiskTargetIncidence,
        highRiskComparatorIncidence = highRiskComparatorIncidence,
        studyStartDate = studyStartDate,
        studyEndDate = studyEndDate,
        dbFile = dbFile,
        cdmDatabaseSchema = cdmDatabaseSchema,
        personsTable = personsTable,
        cohortTable = cohortTable,
        observationPeriodTable = observationPeriodTable
    )

    return(
      list(
          sourceData = data,
          ccData = ccData,
          settings = settings
      )
    )
}

# withr::defer(unlink(defaultDbFile), teardown_env())
