library(RSQLite)

set.seed(176400)

defaultDbFile <- "testDb.sqlite"

# Helper Functions --------------------------------------------------------

# This function takes settings and returns a list of data frames which can be used for testing, including a cohort
# table that can be run through the SQL files. The building blocks of that cohort data can be used to verify the
# correctness of the SQL.
generateTestSourceData <- function(
  n,
  targetId,
  outcomeIds,
  proportionSecondShot,
  timeAtRiskStartDays,
  timeAtRiskEndDays,
  washoutPeriodDays,
  highRiskGroupDefinition,
  matchHighRiskCriteria,
  lowRiskTargetIncidence,
  lowRiskComparatorIncidence,
  highRiskTargetIncidence,
  highRiskComparatorIncidence,
  studyStartDate,
  studyEndDate
) {
  targetDaysEligibleBeforeStudyEndDate <- as.integer(as.Date(studyEndDate) - as.Date(studyStartDate))

  persons <- generateSimulatedPersonsData(n)

  cohort <- generateSimulatedCohortTable(
      persons = persons,
      targetId = targetId,
      outcomeIds = outcomeIds,
      proportionSecondShot = proportionSecondShot,
      timeAtRiskEndDays = timeAtRiskEndDays,
      washoutPeriodDays = washoutPeriodDays,
      highRiskGroupDefinition = highRiskGroupDefinition,
      matchHighRiskCriteria = matchHighRiskCriteria,
      lowRiskTargetIncidence = lowRiskTargetIncidence,
      lowRiskComparatorIncidence = lowRiskComparatorIncidence,
      highRiskTargetIncidence = highRiskTargetIncidence,
      highRiskComparatorIncidence = highRiskComparatorIncidence,
      studyEndDate = studyEndDate,
      targetDaysEligibleBeforeStudyEndDate = targetDaysEligibleBeforeStudyEndDate
  )

  observationPeriods <- generateSimulatedObservationPeriodTable(cohort, washoutPeriodDays)

  targetCohort <- generateTargetCohortFromSimulatedCohortTable(
      cohort,
      targetCohortId = targetId,
      timeAtRiskEndDays = timeAtRiskEndDays
  )

  comparatorCohort <- generateComparatorCohortFromSimulatedTargetCohortTable(
      targetCohort,
      washoutPeriodDays = washoutPeriodDays,
      timeAtRiskEndDays = timeAtRiskEndDays
  )

  strata <- generateStrataFromCohort(targetCohort, persons)

  matchedStrata <- generateMatchedStrataForComparatorCohort(strata, comparatorCohort, persons)

  matchedCohort <- generateMatchedCohort(targetCohort, comparatorCohort, matchedStrata, persons)

  allOutcomes <- getOutcomesForMatchedCohort(
      cohort,
      matchedCohort,
      targetId = targetId,
      outcomeIds = outcomeIds,
      daysFromObsStart = timeAtRiskStartDays,
      daysToObsEnd = timeAtRiskEndDays
  )

  # SQLite does not have datetimes. By default, RSQLite will convert dates to days before/after unix epoch
  # This is not ideal for our purposes because OHDSI tooling, such as the SQL generated by SQL translation functions
  # assumes that dates are stored as dates. Typically, storing the data as unix timestamps, i.e., as the number of
  # seconds since the unix epoch, allows us to work around this problem.
  #
  # For this reason, we will also return SQLite ready dataframes, where dates have been pre-converted to unix timestamps.
  # It's easiest to return the unaltered dataframes, in addition to SQLite ready ones, to allow for easy manipulation.
  sqlitePerson <- persons %>% mutate(
      birth_datetime = as.numeric(as.POSIXct(birth_datetime), format = "%Y-%m-%d")
  )

  sqliteCohort <- cohort %>% mutate(
      cohort_start_date = as.numeric(as.POSIXct(cohort_start_date), format = "%Y-%m-%d"),
      cohort_end_date = as.numeric(as.POSIXct(cohort_end_date), format = "%Y-%m-%d")
  )

  sqliteObservationPeriod <- observationPeriods %>% mutate(
      observation_period_start_date = as.numeric(as.POSIXct(observation_period_start_date), format = "%Y-%m-%d"),
      observation_period_end_date = as.numeric(as.POSIXct(observation_period_end_date), format = "%Y-%m-%d")
  )

  return(
    list(
        cohort = cohort,
        persons = persons,
        observationPeriods = observationPeriods,
        targetCohort = targetCohort,
        comparatorCohort = comparatorCohort,
        strata = strata,
        matchedStrata = matchedStrata,
        matchedCohort = matchedCohort,
        allOutcomes = allOutcomes,
        sqlitePerson = sqlitePerson,
        sqliteCohort = sqliteCohort,
        sqliteObservationPeriod = sqliteObservationPeriod
    )
  )
}

createEmptySQLiteDb <- function(dbFile) {
    con <- dbConnect(RSQLite::SQLite(), dbFile)
    RSQLite::dbDisconnect(con)
}

createPersonsTable <- function(persons, schema, personsTable, dbFile) {
    con <- RSQLite::dbConnect(RSQLite::SQLite(), dbFile)
    RSQLite::dbWriteTable(con, Id(schema = schema, table = personsTable), persons, overwrite = TRUE)
    RSQLite::dbDisconnect(con)
}

createCohortTable <- function(cohort, schema, cohortTable, dbFile) {
    con <- RSQLite::dbConnect(RSQLite::SQLite(), dbFile)
    RSQLite::dbWriteTable(con, Id(schema = schema, table = cohortTable), cohort, overwrite = TRUE)
    RSQLite::dbDisconnect(con)
}

createObservationPeriodTable <- function(observationPeriods, schema, observationPeriodTable, dbFile) {
    con <- RSQLite::dbConnect(RSQLite::SQLite(), dbFile)
    RSQLite::dbWriteTable(con, Id(schema = schema, table = observationPeriodTable), observationPeriods, overwrite = TRUE)
    RSQLite::dbDisconnect(con)
}

scaffoldTestData <- function(
    n = 1000,
    targetId = 666,
    outcomeIds = c(668),
    proportionSecondShot = 1,
    timeAtRiskStartDays = 1,
    timeAtRiskEndDays = 21,
    washoutPeriodDays = 22,
    highRiskGroupDefinition = list(),
    matchHighRiskCriteria = 'all',
    lowRiskTargetIncidence = 0.01,
    lowRiskComparatorIncidence = 0.01,
    highRiskTargetIncidence = 0.01,
    highRiskComparatorIncidence = 0.01,
    studyStartDate = '2020-12-18',
    studyEndDate = '2021-06-30',
    dbFile = "testDb.sqlite",
    cdmDatabaseSchema = "main",
    personsTable = "person",
    cohortTable = "cohort",
    observationPeriodTable = "observation_period"
) {
    createEmptySQLiteDb(dbFile)

    data <- generateTestSourceData(
        n,
        targetId,
        outcomeIds,
        proportionSecondShot,
        timeAtRiskStartDays,
        timeAtRiskEndDays,
        washoutPeriodDays,
        highRiskGroupDefinition,
        matchHighRiskCriteria,
        lowRiskTargetIncidence,
        lowRiskComparatorIncidence,
        highRiskTargetIncidence,
        highRiskComparatorIncidence,
        studyStartDate,
        studyEndDate
    )

    createPersonsTable(data$sqlitePerson, cdmDatabaseSchema, personsTable, dbFile)
    createCohortTable(data$sqliteCohort, cdmDatabaseSchema, cohortTable, dbFile)
    createObservationPeriodTable(data$sqliteObservationPeriod, cdmDatabaseSchema, observationPeriodTable, dbFile)

    sqliteConnectionDetails <- DatabaseConnector::createConnectionDetails(
        dbms = "sqlite",
        server = dbFile
    )

    ccData <- getDbConcurrentComparatorData(connectionDetails = sqliteConnectionDetails,
                                            cdmDatabaseSchema = cdmDatabaseSchema,
                                            targetId = targetId,
                                            outcomeIds = outcomeIds,
                                            studyEndDate = studyEndDate,
                                            exposureDatabaseSchema = cdmDatabaseSchema,
                                            exposureTable = cohortTable,
                                            outcomeDatabaseSchema = cdmDatabaseSchema,
                                            outcomeTable = cohortTable,
                                            timeAtRiskStart = timeAtRiskStartDays,
                                            timeAtRiskEnd = timeAtRiskEndDays,
                                            washoutTime = washoutPeriodDays,
                                            intermediateFileNameStem = NULL)

    settings <- list(
        n = n,
        targetId = targetId,
        outcomeIds = outcomeIds,
        proportionSecondShot = proportionSecondShot,
        timeAtRiskEndDays = timeAtRiskEndDays,
        washoutPeriodDays = washoutPeriodDays,
        highRiskGroupDefinition = highRiskGroupDefinition,
        matchHighRiskCriteria = matchHighRiskCriteria,
        lowRiskTargetIncidence = lowRiskTargetIncidence,
        lowRiskComparatorIncidence = lowRiskComparatorIncidence,
        highRiskTargetIncidence = highRiskTargetIncidence,
        highRiskComparatorIncidence = highRiskComparatorIncidence,
        studyStartDate = studyStartDate,
        studyEndDate = studyEndDate,
        dbFile = dbFile,
        cdmDatabaseSchema = cdmDatabaseSchema,
        personsTable = personsTable,
        cohortTable = cohortTable,
        observationPeriodTable = observationPeriodTable
    )

    return(
      list(
          sourceData = data,
          ccData = ccData,
          settings = settings,
          dbFile = dbFile
      )
    )
}

# withr::defer(unlink(defaultDbFile), teardown_env())
